home_farm/lib/home_farm_web/router.ex
defmodule HomeFarmWeb.Router do
  use HomeFarmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HomeFarmWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/reading-sources", ReadingSourceController
    resources "/sensors", SensorController
  end

  # Other scopes may use custom stacks.
  scope "/api", HomeFarmWeb do
    pipe_through :api

    get "/sensors", PageController, :api_get_sensors
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HomeFarmWeb.Telemetry
    end
  end
end

home_farm/lib/home_farm_web/views/layout_view.ex
defmodule HomeFarmWeb.LayoutView do
  use HomeFarmWeb, :view
end

home_farm/lib/home_farm_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>HomeFarm · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-plcaeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">HomeFarm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= Routes.reading_source_path(@conn, :index) %>">Reading Sources</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= Routes.sensor_path(@conn, :index) %>">Sensors</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <main role="main" class="mt-5 flex-shrink-0">
      <div class="container">
        <%= @inner_content %>
      </div>
    </main>
  
    <%= render_existing @view_module, ~s(#{Path.basename(@view_template, ".html")}_scripts.html), assigns %>
  </body>
</html>